
ALTER TABLE public.production
  ADD COLUMN nb_fruits_echantillon INTEGER DEFAULT 30,
  ADD COLUMN cal_1xxx INTEGER DEFAULT 0,
  ADD COLUMN cal_1xx INTEGER DEFAULT 0,
  ADD COLUMN cal_1x_sup INTEGER DEFAULT 0,
  ADD COLUMN cal_1x_inf INTEGER DEFAULT 0,
  ADD COLUMN cal_2 INTEGER DEFAULT 0,
  ADD COLUMN cal_3 INTEGER DEFAULT 0,
  ADD COLUMN cal_4 INTEGER DEFAULT 0,
  ADD COLUMN cal_5 INTEGER DEFAULT 0,
  ADD COLUMN cal_6 INTEGER DEFAULT 0,
  ADD COLUMN cal_0 INTEGER DEFAULT 0,
  ADD COLUMN cal_1 INTEGER DEFAULT 0,
  ADD COLUMN cal_7 INTEGER DEFAULT 0,
  ADD COLUMN cal_8 INTEGER DEFAULT 0,
  ADD COLUMN cal_10 INTEGER DEFAULT 0,
  ADD COLUMN cal_11 INTEGER DEFAULT 0,
  ADD COLUMN cal_hors_calibre INTEGER DEFAULT 0;
